// <auto-generated />
namespace Land.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fixes8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixes8));
        
        string IMigrationMetadata.Id
        {
            get { return "201302191917415_fixes8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
