// <auto-generated />
namespace Land.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v6Initialise_fixes3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v6Initialise_fixes3));
        
        string IMigrationMetadata.Id
        {
            get { return "201302151013011_v6Initialise_fixes3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
