// <auto-generated />
namespace Land.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Greensheets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Greensheets));
        
        string IMigrationMetadata.Id
        {
            get { return "201303072114159_Greensheets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
