namespace Land.Data.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using Land.Data.Models;
    using WebMatrix;
    using WebMatrix.WebData;
    using System.Web.Security;

    //internal sealed
    public class Configuration : DbMigrationsConfiguration<Land.Data.SiteManagementContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(Land.Data.SiteManagementContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data. E.g.
            //
            //    context.People.AddOrUpdate(
            //      p => p.FullName,
            //      new Person { FullName = "Andrew Peters" },
            //      new Person { FullName = "Brice Lambson" },
            //      new Person { FullName = "Rowan Miller" }
            //    );
            //
            SetupSimpleMembership("LandContext");
            LoadSeedData(context); 
        }

        private void SetupSimpleMembership(string connectionString)
        {
            const string defaultUser = "rwhadmin";
            const string defaultPwd = "admin";
            const string adminRole = "Administrator";
            const string editorRole = "Editor";
            const string accountRole = "Accounts";

            //Initializes the membership system by connecting to a database that contains user information.
            if (!WebSecurity.Initialized)
            {
                WebSecurity.InitializeDatabaseConnection(connectionString, "UserProfile", "UserId", "UserName", autoCreateTables: true);
            }

            if (WebSecurity.Initialized)
            {
                if (Roles.Enabled)
                {
                    if (!Roles.RoleExists(adminRole)) Roles.CreateRole(adminRole);
                    if (!Roles.RoleExists(editorRole)) Roles.CreateRole(editorRole);
                    if (!Roles.RoleExists(accountRole)) Roles.CreateRole(accountRole);

                    if (!WebSecurity.UserExists(defaultUser))
                    {
                        WebSecurity.CreateUserAndAccount(
                          defaultUser,
                          defaultPwd,
                          new { Email = "rwhadmin@rwhland.com", Signature = "Sent from Land Admin" });
                    }

                    if (!Roles.GetRolesForUser(defaultUser).Contains(adminRole))
                    {
                        Roles.AddUsersToRoles(new[] { defaultUser }, new[] { adminRole });
                    }
                }
            }
        }
        private void LoadSeedData(Land.Data.SiteManagementContext context)
        {

            #region Static Ref Data
            context.ProbabilityTypes.AddOrUpdate(
                pt => pt.Id,
                new LandProbabilityType { Id = 1, Name = "NOT SPECIFIED", SortOrder = 100 },
                new LandProbabilityType { Id = 2, Name = "CERTAIN", SortOrder = 100 },
                new LandProbabilityType { Id = 3, Name = "HIGH", SortOrder = 90, },
                new LandProbabilityType { Id = 4, Name = "MED", SortOrder = 60, },
                new LandProbabilityType { Id = 5, Name = "LOW", SortOrder = 30, },
                new LandProbabilityType { Id = 6, Name = "ZERO", SortOrder = 0, }
                );

            context.FieldTypes.AddOrUpdate(
                ft => ft.Id,
                new LandFieldType { Id = 1, Name = "NOT SPECIFIED", SortOrder = 10  },               
                new LandFieldType { Id = 2, Name = "GREENFIELD", SortOrder = 10  },
                new LandFieldType { Id = 3, Name = "BROWNFIELD", SortOrder = 20  },
                new LandFieldType { Id = 4, Name = "BROWN/GREEN", SortOrder = 30  }
                );

            context.StatusTypes.AddOrUpdate(
                st => st.Id,
                new LandStatusType { Id = 1, Code = "TBC", Name = "NOT SPECIFIED", SortOrder = 17  },
                new LandStatusType { Id = 2, Code = "CPD", Name = "Completed", SortOrder = 18  },
                new LandStatusType { Id = 3, Code = "HLD", Name = "On Hold", SortOrder = 19  },
                new LandStatusType { Id = 4, Code = "SAA", Name = "Sold to another agent", SortOrder = 20  },
                new LandStatusType { Id = 5, Code = "WIT", Name = "Withdrawn", SortOrder = 21  },
                new LandStatusType { Id = 6, Code = "ACT", Name = "Active", SortOrder = 22  },
                new LandStatusType { Id = 7, Code = "IMM", Name = "Conditional Exchange - IMM", SortOrder = 23  },
                new LandStatusType { Id = 8, Code = "STR", Name = "Conditional Exchange - STRAT", SortOrder = 24  },
                new LandStatusType { Id = 9, Code = "AVL", Name = "Available", SortOrder = 25  },
                new LandStatusType { Id = 10, Code = "QRY", Name = "Query", SortOrder = 26  },
                new LandStatusType { Id = 11, Code = "EXC", Name = "Exchanged", SortOrder = 27  },
                new LandStatusType { Id = 12, Code = "PEN", Name = "Pending", SortOrder = 28  },
                new LandStatusType { Id = 13, Code = "OEX", Name = "Option Exchanged", SortOrder = 29  },
                new LandStatusType { Id = 14, Code = "STC", Name = "STC", SortOrder = 30  },
                new LandStatusType { Id = 15, Code = "UEX", Name = "Unconditional Exchange", SortOrder = 31  },
                new LandStatusType { Id = 16, Code = "STP", Name = "Subject to Planning", SortOrder = 32  }
                );

            context.Roles.AddOrUpdate(
                r => r.Id,
                new LandRoleType { Id = 1, Name = "OWNER"  },
                new LandRoleType { Id = 2, Name = "BUYER"  },
                new LandRoleType { Id = 3, Name = "AGENT"  },
                new LandRoleType { Id = 4, Name = "LAND AGENT"  },
                new LandRoleType { Id = 5, Name = "AFFILIATE"  },
                new LandRoleType { Id = 6, Name = "SITE OWNER"  },
                new LandRoleType { Id = 7, Name = "SALES REP"  },
                new LandRoleType { Id = 8, Name = "PLANNING APPLICATION AGENT"  },
                new LandRoleType { Id = 9, Name = "CONTRACTOR"  },
                new LandRoleType { Id = 10, Name = "PURCHASER"  },
                new LandRoleType { Id = 11, Name = "SOLICITOR"  },
                new LandRoleType { Id = 12, Name = "COMPANY"  },
                new LandRoleType { Id = 13, Name = "CHARITY"  },
                new LandRoleType { Id = 14, Name = "LOCAL AUTHORITY"  },               
                new LandRoleType { Id = 16, Name = "NEGOTIATOR"  },               
                new LandRoleType { Id = 15, Name = "DISTRICT AUTHORITY"  }
                );

            context.PriorityTypes.AddOrUpdate(
                p => p.Id,
                new LandPriorityType { Id = 1, Name = "HIGH", SortOrder = 90  },
                new LandPriorityType { Id = 2, Name = "MED", SortOrder = 60  },
                new LandPriorityType { Id = 3, Name = "LOW", SortOrder = 30  }
                );

            context.ProjectTypes.AddOrUpdate(
                p => p.Id,
                new LandProjectType { Id = 1, Name = "IMMEDIATE", SortOrder = 6  },
                new LandProjectType { Id = 2, Name = "STRATEGIC", SortOrder = 7  },
                new LandProjectType { Id = 3, Name = "NEW BUILD", SortOrder = 8  },
                new LandProjectType { Id = 4, Name = "CONVERSION", SortOrder = 9  },
                new LandProjectType { Id = 5, Name = "MIXED NEW/CONVERSION", SortOrder = 10  },
                new LandProjectType { Id = 6, Name = "NOT SPECIFIED", SortOrder = 11  }
                );

            context.ConditionalTypes.AddOrUpdate(
                c => c.Id,
                new ConditionalType { Id = 1, Name = "NOT SPECIFIED", SortOrder = 7  },
                new ConditionalType { Id = 2, Name = "CONDITIONAL", SortOrder = 8  },
                new ConditionalType { Id = 3, Name = "UNCONDITIONAL", SortOrder = 9  }
                );

            context.DecissionTypes.AddOrUpdate(
                c => c.Id,                  
                new DecissionType { Id = 4, Name = "NOT SPECIFIED", SortOrder = 1  },               
                new DecissionType { Id = 1, Name = "PENDING", SortOrder = 1  },
                new DecissionType { Id = 2, Name = "ACCEPTED", SortOrder = 2  },
                new DecissionType { Id = 3, Name = "REJECTED", SortOrder = 3  }
                );

            context.AlertActionTypes.AddOrUpdate(
               c => c.Id,
               new AlertActionType { Id = 1, Name = "CALL BACK", SortOrder = 7 },
               new AlertActionType { Id = 2, Name = "BOOK APPOINTMENT", SortOrder = 8},
               new AlertActionType { Id = 3, Name = "SEE COMMENT", SortOrder = 9}
               );

            context.DeliveryTypes.AddOrUpdate(
               c => c.Name,
               new DeliveryType { Id = 1, Name = "PHONE CALL", SortOrder = 1  },
               new DeliveryType { Id = 2, Name = "EMAIL", SortOrder = 2  },
               new DeliveryType { Id = 3, Name = "POST", SortOrder = 3  },
               new DeliveryType { Id = 4, Name = "OTHER", SortOrder = 4  }
               );


            context.PlotTypes.AddOrUpdate(
                p => p.Name,
                new LandPlotType { Id = 1, Name = "TBC", SortOrder = 0  },
                new LandPlotType { Id = 2, Name = "HOUSE", SortOrder = 1  },
                new LandPlotType { Id = 3, Name = "FLAT", SortOrder = 2  },
                new LandPlotType { Id = 4, Name = "TOWNHOUSE", SortOrder = 3  },
                new LandPlotType { Id = 5, Name = "APARTMENT", SortOrder = 4  },
                new LandPlotType { Id = 6, Name = "BUNGALOW", SortOrder = 5  },
                new LandPlotType { Id = 7, Name = "COMMERCIAL UNIT", SortOrder = 6  },
                new LandPlotType { Id = 8, Name = "COMMERCIAL RETAIL", SortOrder = 7  },
                new LandPlotType { Id = 9, Name = "INDUSTRIAL", SortOrder = 8  },
                new LandPlotType { Id = 10, Name = "PLOT", SortOrder = 9  },
                new LandPlotType { Id = 11, Name = "BUNGALOW", SortOrder = 10  },
                new LandPlotType { Id = 12, Name = "COMMERCIAL", SortOrder = 11  }
                );

            context.PlanningTypes.AddOrUpdate(
                p => p.Name,
                new LandPlanningType { Id = 1, Code = "TBC", Name = "TBC", SortOrder = 8  },
                new LandPlanningType { Id = 2, Code = "OUT", Name = "OUT", SortOrder = 9  },
                new LandPlanningType { Id = 3, Code = "FUL", Name = "FULL", SortOrder = 10  },
                new LandPlanningType { Id = 4, Code = "FCO", Name = "FULL and CON", SortOrder = 11  },
                new LandPlanningType { Id = 5, Code = "AP1", Name = "AP1", SortOrder = 12  },
                new LandPlanningType { Id = 6, Code = "COU", Name = "COU", SortOrder = 13  },
                new LandPlanningType { Id = 7, Code = "LBC", Name = "FULL and LBC", SortOrder = 14  }
                );

            context.PlanningApprovalTypes.AddOrUpdate(
                p => p.Name,
                new LandPlanningApprovalStateTypes { Id = 4, Name = "NOT SPECIFIED", SortOrder = 1  },               
                new LandPlanningApprovalStateTypes { Id = 1, Name = "APPROVED", SortOrder = 1  },
                new LandPlanningApprovalStateTypes { Id = 2, Name = "REJECTED", SortOrder = 2  },
                new LandPlanningApprovalStateTypes { Id = 3, Name = "APPEAL", SortOrder = 3  }
                );

          


            #endregion

            #region Static Domain Data

            #region TownData
            /*
            context.Towns.AddOrUpdate(
                t => t.Name,
                new Town { Name = "REIGATE", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LONDON", County = "London", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EDINBURGH", County = "Scotland", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAYES", County = "MIDDLESEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COULSDON", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEST BYFLEET", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FERRING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PARTRIDGE GREEN", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MAYFIELD", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ALDERSHOT", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ALDINGBOURNE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ALDWICK", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ALTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "AMBERLEY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ANDOVER", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ANGMERING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ARDINGLY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ARUNDEL", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ASCOT", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ASH", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ASHFORD", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ASHINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ASHTEAD", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ASHURSTWOOD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BARNHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BARTON ON SEA", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BASILDON", County = "ESSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BASINGSTOKE", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BATTLE", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BEACON HILL", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BECKENHAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BERSTED", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BEVERLEY", County = "HUMBERSIDE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BEXHILL", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BEXHILL ON SEA", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BEXLEY HEATH", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BIDEFORD", County = "DEVON", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BILLINGSHURST", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BINSTED", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BIRCHINGTON", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BIRDHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BISHOPS WALTHAM", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BITTERNE", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BLACKBOYS", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BOGNOR REGIS", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BOLNEY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BORDON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BOSHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BOURNEMOUTH", County = "DORSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BOXGROVE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BRACKLESHAM BAY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BRACKNELL", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BRAMBER", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BRIGHTON", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BROADBRIDGE HEATH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BROADSTAIRS", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BROCKENHURST", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BROMLEY", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BURGESS HILL", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BYFLEET", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CAMBERLEY", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CANTERBURY", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CAPEL", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CATERHAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHANDLERS FORD", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHATHAM", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHEAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHELTENHAM", County = "GLOUCESTERSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHESHUNT", County = "HERTFORDSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHICHESTER", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHIDHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHINEHAM", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHIPPING NORTON", County = "OXFORDSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHIPPING ONGAR", County = "ESSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHRISTCHURCH", County = "DORSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CLANFIELD", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CLAPHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CLIMPING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COLDEN COMMON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COLDWALTHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COLGATE", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COOLHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COPTHORNE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CORHAMPTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COWPLAIN", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CRANLEIGH", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CRAWLEY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CRAWLEY DOWN", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CROSS IN HAND", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CROWBOROUGH", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CROWHURST", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CROYDON", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CUCKFIELD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DANEHILL", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DARTFORD", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DENMEAD", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DENTON", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DIAL POST", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DIBDEN PURLIEU", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DISS", County = "NORFOLK", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DITCHLING", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DONNINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DORKING", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DOVER", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DRAYTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DURLEY", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EASEBOURNE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EAST GRINSTEAD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EAST HOATHLY", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EAST MOLESEY", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EAST PRESTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EASTBOURNE", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EASTERGATE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EASTLEIGH", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EDENBRIDGE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EGHAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ELSTEAD", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EMSWORTH", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ESHER", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FAREHAM", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FARNHAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FAYGATE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FELPHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FERNHURST", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FINDON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FINDON VALLEY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FISHBOURNE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FLANSHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FLEET", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FLIMWELL", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FOLKSTONE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FONTWELL", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FORD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FOREST GREEN", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FOUR MARKS", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GLOUCESTER", County = "HERTFORDSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GODALMING", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GODDARDS GREEN", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GORING BY SEA", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GOSPORT", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GREAT MISSENDEN", County = "BUCKINGHAMSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GUILDFORD", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HALNAKER", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAMBLE", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAMBROOK", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAMMER", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAMPTON", County = "MIDDLESEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HANDCROSS", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HARRIETSHAM", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HARTLEY", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HASLEMERE", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HASSOCKS", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HASTINGS", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAVANT", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAYLING ISLAND", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAYWARDS HEATH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HEADLEY", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HEATHFIELD", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HEATHROW", County = "MIDDLESEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HELLINGLY", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HENFIELD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HIGH WYCOMBE", County = "BUCKINGHAMSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HIGHCLIFFE", County = "DORSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HOOK", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HORAM", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HORLEY", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HORNDEAN", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HORSHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HOVE", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HUNGERFORD", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HUNSTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HURSTPIERPOINT", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HYTHE", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "IFOLD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ISLE OF SHEPPY", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ITCHENOR", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "KENLEY", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "KINGSTON UPON THAMES", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "KINGSWOOD", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "KIRDFORD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LAMBOURNE", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LANCING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LAVANT", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LEAMINGTON SPA", County = "WARWICKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LEATHERHEAD", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LEE ON SOLENT", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LEWES", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LIMPSFIELD", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LINDFIELD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LINGFIELD", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LIPHOOK", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LISS", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LITTLEHAMPTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LOWER BEEDING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LOWER DICKER", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LOXWOOD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LUGERSHALL", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LYMINGTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LYMINSTER", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MAIDENBOWER", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MAIDSTONE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MIDDLESBROUGH", County = "WEST MIDLANDS", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MIDDLETON ON SEA", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MIDHURST", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MILE OAK", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NETHERNE", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NETHERNE ON THE HILL", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NETLEY", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NEW MILTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NEWBURY", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NEWDIGATE", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NEWHAVEN", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NEWICK", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NORWICH", County = "NORFOLK", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NOTTINGHAM", County = "NOTTINGHAMSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NUTBOURNE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "OCKLEY", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "OLD WOKING", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ORPINGTON", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "OVING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "OVINGDEAN", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "OXFORD", County = "OXFORDSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "OXFORD{SALEPNDA}", County = "OXFORDSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "OXTED", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PAGHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PARK GATE", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PATCHAM", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PEACEHAVEN", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PEASE POTTAGE", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PETERSFIELD", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PETWORTH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PEWSEY", County = "WILTSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PLUCKLEY", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "POLEGATE", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "POOLE", County = "DORSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PORTCHESTER", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PORTSLADE", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PORTSMOUTH", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PULBOROUGH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PURLEY", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "READING", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "REDHILL", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "RINGMER", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ROMSEY", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ROSEGREEN", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ROWLANDS CASTLE", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "RUNCTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "RUSTINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "RYE", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SALISBURY", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SALTDEAN", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SALVINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SANDHURST", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SARISBURY GREEN", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SAYERS COMMON", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SCAYNES HILL", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SEAFORD", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SELMESTON", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SELSEY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SEND", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SEVENOAKS", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHEPPERTON", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHINFIELD", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHOREHAM BY SEA", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHORHAM HARBOUR", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHRIPNEY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SIDLESHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SINGLETON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SLINFOLD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SMALL DOLE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SMALLFIELD", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTH HARTING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTHAMPTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTHBOURNE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTHSEA", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTHWATER", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTHWICK", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ST LEONARDS ON SEA", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "STAPLEHURST", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "STEYNING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "STORRINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "STROUD", County = "GLOUCESTERSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "STUBBINGTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SUNBURY ON THAMES", County = "MIDDLESEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SUTTON", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SWANWICK", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TANGMERE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TAUNTON", County = "SOMERSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TAVISTOCK", County = "DEVON", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TEDDINGTON", County = "MIDDLESEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TENTERDEN", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "THAKEHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "THURSLEY", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TITCHFIELD COMMON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TONBRIDGE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TOTLAND BAY", County = "ISLE OF WIGHT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TOTTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TUNBRIDGE WELLS", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "UCKFIELD", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "UPPER BEEDING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "VARIOUS", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "VERWOOD", County = "DORSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "VIRGINIA WATER", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WALBERTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WALTHAM CHASE", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WALTON ON THAMES", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WARSASH", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WASHINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WATERLOOVILLE", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WATERSFIELD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEST ASHLING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEST CHILTINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEST MARDEN", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEST WITTERING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WESTERGATE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WESTFIELD", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WESTHAMPNETT", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEYBRIDGE", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WHITCHURCH", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WHITELEY", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WHITEPARISH", County = "WILTSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WHITSTABLE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WICK", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WICKHAM", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WIMBLEDON", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WINCHESTER", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WISBOROUGH GREEN", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WIVELSFIELD", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WIVELSFIELD GREEN", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WOKINGHAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WOODGATE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WOODINGDEAN", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WOOLSTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WORTHING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WROTHAM", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "YAPTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "YEOVIL", County = "SOMERSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "KINGSWORTHY", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "THANET", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "STROOD", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CAMELSDALE", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "THATCHAM", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EDGEWARE", County = "MIDDLESEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EAST WITTERING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "RUDGWICK", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NYETIMBER", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DURRINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEST WORTHING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GORING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HIGH SALVINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LAVERSTOCK", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DUNCTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EAST HAVANT", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LODSWORTH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WESTBOURNE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EARNLEY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ALDEBURGH", County = "SUFFOLK", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "APPLEDRAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "AYLESFORD", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BALCOMBE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BALDOCK", County = "HERTFORDSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BARCOMBE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BEDHAMPTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BEDHAMPTON HILL", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BELMONT", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BEMBRIDGE", County = "ISLE OF WIGHT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BEPTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BILLINGBOROUGH", County = "LINCS", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BLACKBOYS VILLAGE", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BLENDWORTH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BOGNOR REGIS/FELPHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BOLNORE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BRENTFORD", County = "MIDDLESEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BRIDPORT", County = "DORSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BROCKHAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BUCKHURST HILL", County = "ESSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BURITON VILLAGE", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BURY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BUXTED", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CALNE", County = "WILTSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHAILEY", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHARTHAM", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHERTSEY", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHIPPENHAM", County = "WILTSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHISLEHURST", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHRISTS HOSPITAL", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHUCH HATCH", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CLIMPING/CLYMPING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CLYMPING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COCKING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CORSHAM", County = "WILTSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COSHAM", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COSTA BLANCA", County = "SPAIN", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COSTA DEL SOL ETC", County = "SPAIN", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COWFOLD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CUCKFIELD/LEYTON LEA", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CUXTON", County = "ROCHESTER", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DORCHESTER", County = "DORSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EAST MEON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EASTRY", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ELMER", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "EPSOM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FAIR OAK", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FARNBOROUGH", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FAVERSHAM", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FITTLEWORTH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FIVE OAKS", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FOREST ROW", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FROXFIELD", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FUNTINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GRAFFHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GRAVESEND", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HARROGATE", County = "YORKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HARROW", County = "MIDDLESEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HASELMERE", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAWKINGE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HEDGE END", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HIGHFIELD", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HIGHLEIGH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HILTINGBURY", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HINDHEAD", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HORTON KIRBY", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ISLEWORTH", County = "MIDDLESEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "IWADE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "KEW", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "KINGSFOLD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "KINGSTON LEY", County = "LIPHOOK", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "KNOWLE VILLAGE", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LA MANGA", County = "SPAIN", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LEWISHAM", County = "LONDON", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LIDSEY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LINDFIELD COMMON", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LLANISHEN", County = "CARDIFF", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LOCKHEATH", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LONGHOUGHTON", County = "NORTHUMBERLAND", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MAIDENHEAD", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MARBELLA", County = "SPAIN", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MARESFIELD", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MARESFIELD PARK", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MELKSHAM", County = "WILTSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MIDDLETON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NORTH BERSTED", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NORTH CHAPEL", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NORTHFLEET", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NUTLEY", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "OLD PORTSMOUTH", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PETMORTH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PRESTBURY (MANCHESTER)", County = "CHESHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PRINSTED", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PYECOMBE VILLAGE", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "RAMSGATE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "RINGWOOD", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ROCHESTER", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ROTHERFIELD", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ROTTINGDEAN", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ROYAL TUNBRIDGE WELLS", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "RUSPER", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SE1", County = "LONDON", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SEATON", County = "DEVON", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SELLINDGE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHERMANBURY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHILBOTTLE", County = "NORTHUMBERLAND", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHIREMOOR", County = "TYNE & WEAR", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHIRLEY", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHIRRELL HEATH", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHOREHAM (BEACH)", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SINGLETON HILL", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SITTINGBOURNE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTH CHAILEY", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTH MARSTON", County = "WILTSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTH MUNDHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTHBORNE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SPENNYMOOR", County = "DURHAM", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "STONE CROSS", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SUMMERLEY", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SUMMERSDALE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SURBITON", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SUTTON COLDFIELD", County = "WEST MIDLANDS", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SW11", County = "LONDON", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SW5", County = "LONDON", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TARRING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "THREE BRIDGES", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TORTINGTON", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TWICKENHAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TWYFORD", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "UNKNOWN", County = "UNKNOWN", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "UPNOR", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WATFORD", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WADHURST", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WARNHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WARNHAM VILLAGE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WAYBRIDGE", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEST GRINSTEAD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEST MALLING", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEST TOTTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WESTGATE/CHICHESTER", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WEYMOUTH", County = "DORSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WHITESMITH", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WHITESMITH (NR LEWES)", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WINCHMORE HILL", County = "LONDON", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WINDSOR", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WOKING", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WORTH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WRENS WARRAN", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CAMBOURNE", County = "CORNWALL", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HORSTED KEYNES", County = "SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HARTFIELD", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHIPPING CAMDEN", County = "GLOUCESTERSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PIRBRIGHT", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAILSHAM", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHOLDERTON", County = "WILTSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HERMITAGE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MANCHESTER", County = "LANCS", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "STOKE ON TRENT", County = "STAFFORDSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WICKFORD", County = "ESSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GROVE", County = "OXFORDSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ARLINGTON", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HEMEL HEMPSTEAD", County = "HERTFORDSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "IPSWICH", County = "SUFFOLK", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "IFIELD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NORTH CHEAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BEARE GREEN", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTHALL", County = "LONDON", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "COBHAM", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHOREHAM", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WARBLINGTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOUTH WONSTON", County = "HAMPSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHREWTON", County = "WILTSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "N UTLEY", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LIVERPOOL", County = "MERSEYSIDE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NUTLEY (EAST SUSSEX)", County = "EAST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "AMMANFORD", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ASH VALE", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ATTLEBOROUGH", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BAYDON", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BERSTEAD", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BROAD OAK", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BROOKWOOD", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BULGARIA", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHELWOOD GATE", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CHESSINGTON", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "CRANBROOK", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DONCASTER", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DYMCHURCH", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FELBRIDGE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FOLKESTONE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "FRITH END", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GILLINGHAM", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "GRAYS", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HACKNEY", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HAWKHURST", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "HERNE BAY", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "ISFIELD", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "LUDGERSHALL", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MALVERN", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MANSFIELD", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "MARGATE", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NEW ALRESFORD", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NEWPORT", County = "GWENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NORTH LANCING", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NR HINDHEAD", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "NR. UCKFIELD", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "PUDDLETOWN", County = "DORSET", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHARPTHORNE", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SHOREHAM BEACH", County = "WEST SUSSEX", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SINDLESHAM", County = "BERKSHIRE", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOLIHULL", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SOMPTING", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SPAIN", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "STANSTEAD", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "STREATHAM COMMON", County = "LONDON", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SURREY", County = "SURREY", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "SWINDON", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "TODDINGTON", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WESTERHAM", County = "KENT", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "WESTHAM", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "OSWESTRY", County = "Shropshire", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "DYFFED", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BANSTEAD", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  },
                new Town { Name = "BA", County = "", Country = "UK", Postcode = "", Latitude = "0", Longditude = "0"  }
                );
            */
            #endregion

            // todo - create Load tool to import historical database content. 

            #endregion


     

        }
    }
}
